oecd = read.table('ocdeb.txt', header = T, sep = "\t")
View(oecd)
dim(oecd)
str(oecd)
summary(oecd)
boxplot(oecd$birth_rate ~ oecd$country)
oecd_noIR = subset(oecd, oecd$country != 'IR')
boxplot(oecd_noIR$birth_rate)
install.packages("tables")

library(tables)
library(psych)

tabular(oecd$country~1*(n=1 + Percent('col')))
boxplot(oecd$unemployement_rate ~ oecd$country)
boxplot(oecd$unemployement_rate)
cor(oecd$birth_rate, oecd$unemployement_rate)
cor.test(oecd$birth_rate, oecd$unemployment, method = 'spearman')
cor(oecd$birth_rate, oecd$GDP)

hist(oecd_noIR$birth_rate, freq = F, breaks = 10)
describe(oecd_noIR$birth_rate)
shapiro.test(oecd$birth_rate)
shapiro.test((oecd_noIR$birth_rate))
shapiro.test(oecd$unemployement_rate)
shapiro.test(oecd$percentage_of_worker_primary_sector)
shapiro.test(oecd)
